// packages/backend/src/app.ts
import express, { Response as ExResponse, Request as ExRequest, NextFunction } from 'express';
import pinoHttp from 'pino-http';
import { logger } from './utils/logger';
import { RegisterRoutes } from './generated/routes'; // Auto-generated by TSOA!
import { ivrRouter } from './ivr/ivr.router';

export const app: express.Application = express();

// 1. Middleware
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Attach Pino to log all HTTP requests automatically
app.use(
  pinoHttp({
    logger,
    autoLogging: {
      ignore: (req) => req.url === '/health' // Ignore health checks to prevent log spam
    }
  })
);

// 2. Mount API Routes (Generated by TSOA)
RegisterRoutes(app);
// Mount Yemot Router
app.use('/ivr',ivrRouter);

// 3. Global Error Handler for API
app.use(function errorHandler(
  err: unknown,
  req: ExRequest,
  res: ExResponse,
  next: NextFunction
): ExResponse | void {
  if (err instanceof Error) {
    if (err.message === 'No token provided' || err.message === 'Invalid or expired token') {
      return res.status(401).json({ message: 'Unauthorized' });
    }
    if (err.message === 'Invalid username or password') {
      return res.status(401).json({ message: err.message });
    }
    
    // Catch validation errors generated by TSOA (e.g., missing body parameters)
    if ((err as any).status === 422) {
      return res.status(422).json({
        message: "Validation Failed",
        details: (err as any).fields,
      });
    }

    logger.error({ err }, 'Unhandled API Error');
    return res.status(500).json({ message: 'Internal Server Error' });
  }

  next();
});